[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --prod=false && echo '=== BUILDING ALL PACKAGES ===' && pnpm -r --filter './packages/core/**' --filter './packages/agents/**' build && echo '=== BUILD COMPLETE ===' && ls -la packages/core/mcp-server/dist/ && echo '=== CHECKING server.js ===' && if test -f packages/core/mcp-server/dist/server.js; then echo '✅✅✅ server.js EXISTS! ✅✅✅'; else echo '❌ server.js NOT FOUND!'; echo 'Files in mcp-server/dist:'; find packages/core/mcp-server/dist -type f 2>/dev/null || echo 'dist directory does not exist'; echo 'All dist directories:'; find packages -type d -name dist 2>/dev/null; exit 1; fi && echo '✅✅✅ READY TO DEPLOY! ✅✅✅'"

[deploy]
startCommand = "cd /app && node packages/core/mcp-server/dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
