[build]
builder = "NIXPACKS"
buildCommand = "cd /app && pnpm install && pnpm --filter @frogface/core-mcp build"

[deploy]
startCommand = "cd packages/core/mcp-server && pnpm start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
