[build]
builder = "NIXPACKS"
buildCommand = "cd /app && pnpm install --prod=false && cd packages/core/mcp-server && pnpm build"

[deploy]
startCommand = "node packages/core/mcp-server/dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
