[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --prod=false && cd packages/core/api-client && pnpm build && cd ../knowledge-base && pnpm build && cd ../agent-base && pnpm build && cd ../../agents/copywriter && pnpm build && cd ../archivist && pnpm build && cd ../edison-copywriter && pnpm build && cd ../../core/mcp-server && pnpm build && cd /app && ls -la packages/core/mcp-server/dist/"

[deploy]
startCommand = "cd /app && node packages/core/mcp-server/dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
