[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --prod=false && cd packages/core/api-client && pnpm build && cd ../knowledge-base && pnpm install && pnpm build && cd ../agent-base && pnpm install && pnpm build && cd ../../agents/copywriter && pnpm install && pnpm build && cd ../archivist && pnpm install && pnpm build && cd ../edison-copywriter && pnpm install && pnpm build && cd ../../core/mcp-server && pnpm install && pnpm build 2>&1 | tee build.log && cd /app && echo '=== BUILD RESULTS ===' && cat packages/core/mcp-server/build.log 2>/dev/null || echo 'No build log' && ls -la packages/core/mcp-server/dist/ && test -f packages/core/mcp-server/dist/server.js && echo '✅ server.js exists!' || echo '❌ server.js NOT FOUND!'"

[deploy]
startCommand = "cd /app && node packages/core/mcp-server/dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
