[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --prod=false && pnpm build"

[deploy]
startCommand = "cd /app && node packages/core/mcp-server/dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
