[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --prod=false && pnpm --filter '@frogface/core-api-client' build && pnpm --filter '@frogface/core-knowledge-base' build && pnpm --filter '@frogface/core-agent-base' build && pnpm --filter '@frogface/agent-copywriter' build && pnpm --filter '@frogface/agent-archivist' build && pnpm --filter '@frogface/agent-edison-copywriter' build && pnpm --filter '@frogface/core-mcp' build || (echo 'Build error!' && exit 1)"

[deploy]
startCommand = "node packages/core/mcp-server/dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
