[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm --filter @frogface/core-mcp run build"

[deploy]
startCommand = "pnpm --filter @frogface/core-mcp run railway:start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
