[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm --filter @frogface/core-mcp build"

[deploy]
startCommand = "cd packages/core/mcp-server && node dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
