[build]
builder = "NIXPACKS"
buildCommand = "pnpm install"

[deploy]
startCommand = "cd packages/core/mcp-server && pnpm exec tsx src/server.ts"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
