[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --prod=false && pnpm --filter @frogface/core-mcp run build"

[deploy]
startCommand = "node packages/core/mcp-server/dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
