[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --prod=false && pnpm --filter ./packages/core/api-client build && pnpm --filter ./packages/core/knowledge-base build && pnpm --filter ./packages/core/agent-base build && pnpm --filter ./packages/agents/copywriter build && pnpm --filter ./packages/agents/archivist build && pnpm --filter ./packages/agents/edison-copywriter build && pnpm --filter ./packages/core/mcp-server build"

[deploy]
startCommand = "node packages/core/mcp-server/dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
