[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --prod=false --ignore-scripts && cd packages/core/mcp-server && pnpm install --ignore-scripts && pnpm build"

[deploy]
startCommand = "node packages/core/mcp-server/dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
