[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --prod=false && pnpm -r --filter './packages/core/**' --filter './packages/agents/**' build && echo '=== CHECKING BUILD ===' && ls -R packages/*/dist 2>/dev/null | head -20 && ls -la packages/core/mcp-server/dist/ 2>&1 && echo '=== SERVER.JS CHECK ===' && test -f packages/core/mcp-server/dist/server.js && echo '✅ server.js EXISTS!' || (echo '❌ server.js NOT FOUND!' && find packages -name 'server.js' 2>/dev/null)"

[deploy]
startCommand = "cd /app && node packages/core/mcp-server/dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
